### PR TITLE
smaller default timeout 

### PR DESCRIPTION
**Pull request by xiaoxuanzi**
I change default timeout  since the following message：

D:\python3.5.2\python.exe D:/jobq-1/example/example.py
Traceback (most recent call last):
  File "D:/jobq-1/example/example.py", line 16, in <module>
    jobq.run([0, 1, 2], [add1, printarg])
  File "D:\jobq-1\jobq.py", line 72, in run
    th.join(endtime - time.time())
  File "D:\python3.5.2\lib\threading.py", line 1058, in join
1
2
3
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "D:\python3.5.2\lib\threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
OverflowError: timeout value is too large

Process finished with exit code 1

### CODE REVIEW

**Comment by drmingdrmer** [comment]
OK. It would be more rational using a smaller timeout.

**Comment by drmingdrmer** [comment]
OK. It would be more reasonable using a smaller timeout.

But 86400 seconds(one day) is too small since `timeout=None` implies there is no timeout.
Some times a job would run for a very long time(such as scanning/cleaning files in a large storage service system), maybe several days or weeks.

Thus maybe 86400 X 356 is a reasonable timeout value?

**Comment by drmingdrmer** [comment]
Merged and another test is added to address this issue.

**Comment by xiaoxuanzi** [comment]
I GOT IT, THX!

**Pull request merged**
